In [ ]:
import os
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import math
from sklearn.cluster import KMeans 
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt
from matplotlib import animation, colors
from sklearn.cluster import KMeans
from sklearn import preprocessing as sk_preprocessing
from sklearn.metrics import accuracy_score #scoring
from sklearn.metrics import confusion_matrix
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Flatten, Dense, Dropout
from tensorflow.keras import datasets, layers, models
from keras.callbacks import EarlyStopping
from tensorflow.keras.callbacks import TensorBoard

In [ ]:
pressure = '/Users/votri/Downloads/DSDA 385 Machine Learning/Final Project - Climate Change/Pressure/MinMaxNormWithLabel/'

wind = '/Users/votri/Downloads/DSDA 385 Machine Learning/Final Project - Climate Change/CESMU200/MinMaxNormWithLabel/'

# Get the list of subfolders
subfolders = [subfolder for subfolder in os.listdir(pressure) if os.path.isdir(os.path.join(pressure, subfolder))]

dfs_pressure = []
dfs_wind = []
reshaped_arrays = []
folder_names = []

for subfolder in subfolders:
    pressure_path = os.path.join(pressure, subfolder)
    wind_path = os.path.join(wind, subfolder)
    files = [f for f in os.listdir(pressure_path) if f.endswith('.csv')]
    for file in files:
        # pressure data
        pressure_file_path = os.path.join(pressure_path, file)
        df_pressure = pd.read_csv(pressure_file_path, header=None)
        df_pressure = np.array(df_pressure)
        dfs_pressure.append(df_pressure)
        
        # wind data
        wind_file_path = os.path.join(wind_path, file)
        df_wind = pd.read_csv(wind_file_path, header=None)
        df_wind = np.array(df_wind)
        dfs_wind.append(df_wind)
        
        # stack 2 arrays
        df = np.dstack((df_pressure, df_wind))
        (h,w,c) = df.shape
        df_2D = df.reshape(h*w,c) # reshape df to 2D
        
        reshaped_array = np.reshape(df, (1,-1)) # Reshape the dataframe into a 1D array with 225 attributes
        reshaped_arrays.append(reshaped_array)  # Append the reshaped array to the list
        
        folder_names.append(subfolder) # Save the class of the image
        
# Concatenate the reshaped arrays into a single array
concatenated_array = np.concatenate(reshaped_arrays, axis=0)

# Convert the concatenated array into a dataframe
result_df = pd.DataFrame(concatenated_array)
result_df['Class'] = folder_names

In [ ]:
print(result_df)
result_df.describe()

            0         1         2         3         4         5         6  \
0    0.139692  0.000000  0.139077  0.000000  0.137846  0.000000  0.137231   
1    0.475692  0.222222  0.473846  0.218182  0.471385  0.196429  0.468923   
2    0.248615  0.106383  0.243692  0.083333  0.240000  0.062500  0.237538   
3    0.248615  0.106383  0.243692  0.083333  0.240000  0.062500  0.237538   
4    0.293538  0.208333  0.284923  0.163265  0.278154  0.120000  0.272615   
..        ...       ...       ...       ...       ...       ...       ...   
732  0.844923  0.400000  0.857231  0.312500  0.872615  0.272727  0.886154   
733  0.912615  0.205882  0.915692  0.228571  0.923692  0.184211  0.929846   
734  0.931077  0.305556  0.933538  0.315068  0.931692  0.328767  0.931692   
735  0.868923  0.603774  0.875077  0.509091  0.880000  0.413793  0.883692   
736  0.856000  0.028986  0.864000  0.014706  0.874462  0.058824  0.876923   

            7         8         9  ...       441       442       443  \
0  

0           1           2           3           4           5    \
count  737.000000  737.000000  737.000000  737.000000  737.000000  737.000000   
mean     0.653576    0.304457    0.652917    0.293300    0.652001    0.282113   
std      0.259836    0.283046    0.261524    0.281538    0.262980    0.278370   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.483692    0.062500    0.480000    0.056604    0.478769    0.053333   
50%      0.719385    0.211538    0.721231    0.188679    0.721231    0.181818   
75%      0.882462    0.514286    0.888615    0.490566    0.894769    0.486486   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

              6           7           8           9    ...         440  \
count  737.000000  737.000000  737.000000  737.000000  ...  737.000000   
mean     0.650932    0.271847    0.649845    0.263561  ...    0.643169   
std      0.264169    0.276129    0.265151    0.274591  ...    0.279557   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.473846    0.051282    0.468308    0.041667  ...    0.447385   
50%      0.716923    0.163636    0.710769    0.156250  ...    0.709538   
75%      0.899692    0.437500    0.901538    0.424242  ...    0.903385   
max      1.000000    1.000000    1.000000    1.000000  ...    0.995077   

              441         442         443         444         445         446  \
count  737.000000  737.000000  737.000000  737.000000  737.000000  737.000000   
mean     0.476756    0.647061    0.472584    0.652169    0.468764    0.658171   
std      0.277604    0.279201    0.276394    0.278348    0.275974    0.277009   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.265306    0.451077    0.254902    0.459692    0.254902    0.467692   
50%      0.518072    0.713231    0.500000    0.719385    0.500000    0.726154   
75%      0.687500    0.910154    0.690141    0.916308    0.681319    0.918769   
max      1.000000    0.992000    1.000000    0.988308    1.000000    0.986462   

              447         448         449  
count  737.000000  737.000000  737.000000  
mean     0.465328    0.664773    0.463245  
std      0.276022    0.275190    0.277787  
min      0.000000    0.000000    0.000000  
25%      0.256410    0.478154    0.250000  
50%      0.488372    0.736000    0.472727  
75%      0.674157    0.922462    0.673077  
max      1.000000    0.987692    1.000000  

[8 rows x 450 columns]

In [ ]:
counts = result_df['Class'].value_counts()
print(counts)

COL     327
CL      178
COH     161
NROI     71
Name: Class, dtype: int64


In [ ]:
X = result_df.drop('Class', axis = 1)
Y = result_df['Class']

Y_numerized = Y.replace({'CL': 0, 'COL' : 2, 'COH': 3, 'NROI': 1})
print(Y_numerized)

0      0
1      0
2      0
3      0
4      0
      ..
732    1
733    1
734    1
735    1
736    1
Name: Class, Length: 737, dtype: int64


In [ ]:
X_3D = X.to_numpy().reshape(X.shape[0], 15, 15, 2)
print(X_3D)

[[[[0.139692 0.      ]
   [0.139077 0.      ]
   [0.137846 0.      ]
   ...
   [0.150154 0.036364]
   [0.153846 0.018868]
   [0.156923 0.019608]]

  [[0.136    0.      ]
   [0.134154 0.      ]
   [0.131692 0.      ]
   ...
   [0.138462 0.018182]
   [0.142154 0.      ]
   [0.146462 0.      ]]

  [[0.132308 0.025641]
   [0.129846 0.025641]
   [0.126154 0.      ]
   ...
   [0.124923 0.      ]
   [0.129846 0.      ]
   [0.134769 0.      ]]

  ...

  [[0.150154 0.358974]
   [0.138462 0.384615]
   [0.125538 0.384615]
   ...
   [0.069538 0.309091]
   [0.075692 0.301887]
   [0.084308 0.313725]]

  [[0.158769 0.384615]
   [0.146462 0.410256]
   [0.133538 0.410256]
   ...
   [0.076923 0.345455]
   [0.081846 0.358491]
   [0.091692 0.372549]]

  [[0.167385 0.410256]
   [0.155692 0.410256]
   [0.142769 0.435897]
   ...
   [0.086154 0.4     ]
   [0.092308 0.415094]
   [0.102769 0.431373]]]


 [[[0.475692 0.222222]
   [0.473846 0.218182]
   [0.471385 0.196429]
   ...
   [0.446769 0.016129]
   [0.448 

In [ ]:
# train and test split
train_x, test_x, train_y, test_y = train_test_split(X_3D, Y_numerized, test_size=0.3, random_state=42)
print(train_x.shape, train_y.shape, test_x.shape, test_y.shape) # check the shapes

(515, 15, 15, 2) (515,) (222, 15, 15, 2) (222,)


In [ ]:
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=3, activation='relu', input_shape=(15,15,2)))
model.add(Conv2D(filters=64, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))

model.add(Flatten())
#model.add(Dense(128, activation='relu'))
#model.add(Dense(64, activation='relu'))
model.add(Dense(4, activation='softmax'))

model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
# Train the model
early_stopping = EarlyStopping(monitor='loss', patience=30)
tensorboard_callback = TensorBoard(log_dir="./logs")
model.fit(train_x, train_y, epochs=1000, batch_size=32, callbacks=[tensorboard_callback, early_stopping])

Epoch 1/1000
17/17 [==============================] - 2s 16ms/step - loss: 1.2245 - accuracy: 0.4796
Epoch 2/1000
17/17 [==============================] - 0s 14ms/step - loss: 0.8427 - accuracy: 0.7282
Epoch 3/1000
17/17 [==============================] - 0s 15ms/step - loss: 0.5769 - accuracy: 0.7670
Epoch 4/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.5348 - accuracy: 0.7767
Epoch 5/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.4842 - accuracy: 0.8019
Epoch 6/1000
17/17 [==============================] - 0s 15ms/step - loss: 0.4699 - accuracy: 0.8078
Epoch 7/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.4888 - accuracy: 0.7942
Epoch 8/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.4683 - accuracy: 0.8097
Epoch 9/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.4370 - accuracy: 0.8058
Epoch 10/1000
17/17 [==============================] - 0s 14ms/step - loss: 0.4368 - accura

17/17 [==============================] - 0s 15ms/step - loss: 0.2821 - accuracy: 0.8816
Epoch 82/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.2673 - accuracy: 0.8777
Epoch 83/1000
17/17 [==============================] - 0s 15ms/step - loss: 0.2764 - accuracy: 0.8796
Epoch 84/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.2846 - accuracy: 0.8680
Epoch 85/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.2687 - accuracy: 0.8874
Epoch 86/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.2709 - accuracy: 0.8854
Epoch 87/1000
17/17 [==============================] - 0s 17ms/step - loss: 0.3186 - accuracy: 0.8505
Epoch 88/1000
17/17 [==============================] - 0s 15ms/step - loss: 0.3091 - accuracy: 0.8680
Epoch 89/1000
17/17 [==============================] - 0s 15ms/step - loss: 0.2691 - accuracy: 0.8971
Epoch 90/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.2833 - accuracy: 0

17/17 [==============================] - 0s 14ms/step - loss: 0.2179 - accuracy: 0.9010
Epoch 161/1000
17/17 [==============================] - 0s 15ms/step - loss: 0.2175 - accuracy: 0.9126
Epoch 162/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.1985 - accuracy: 0.9320
Epoch 163/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.1975 - accuracy: 0.9184
Epoch 164/1000
17/17 [==============================] - 0s 16ms/step - loss: 0.1949 - accuracy: 0.9184
Epoch 165/1000
17/17 [==============================] - 0s 15ms/step - loss: 0.2146 - accuracy: 0.9087
Epoch 166/1000
17/17 [==============================] - 0s 15ms/step - loss: 0.2262 - accuracy: 0.9029
Epoch 167/1000
17/17 [==============================] - 0s 14ms/step - loss: 0.1892 - accuracy: 0.9282
Epoch 168/1000
17/17 [==============================] - 0s 14ms/step - loss: 0.2153 - accuracy: 0.8951
Epoch 169/1000
17/17 [==============================] - 0s 18ms/step - loss: 0.1943 - ac

17/17 [==============================] - 0s 14ms/step - loss: 0.1428 - accuracy: 0.9417


In [ ]:
# Use the trained model to make predictions on the test set
y_pred = model.predict(test_x).argmax(axis=1)

# Calculate the accuracy of the model on the test set
accuracy = accuracy_score(test_y, y_pred)
print('Test accuracy:', accuracy)

Test accuracy: 0.8603603603603603


In [ ]:
cm = confusion_matrix(test_y, y_pred)
print(cm)

[[47  0 11  0]
 [ 0 12  7  2]
 [ 6  1 84  1]
 [ 0  1  2 48]]


model.add(Conv2D(filters=128, kernel_size=3, activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2)))
model.add(Dropout(0.25))